# Generated by Django 6.1.2 on 2026-10-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Имя Художника', max_length=200, verbose_name='Имя художника')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('statement', models.TextField(blank=True, verbose_name='Artist statement')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artist/', verbose_name='Фото художника')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('whatsapp', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='artist/', verbose_name='CV (PDF)')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Профиль художника',
                'verbose_name_plural': 'Профиль художника',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения с формы',
                'ordering': ['-created_at'],
            },
        ),
    ]
