# Generated by Django 6.1.2 on 2026-10-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True, verbose_name='Slug')),
                ('venue', models.CharField(max_length=220, verbose_name='Площадка')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
                'ordering': ['-date_start'],
            },
        ),
    ]
