# Generated by Django 6.1.2 on 2026-10-07 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True, verbose_name='Slug')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('technique', models.CharField(blank=True, help_text='Например: холст, масло', max_length=220, verbose_name='Техника')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Ширина, см')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Высота, см')),
                ('description', models.TextField(blank=True, verbose_name='История картины')),
                ('image', models.ImageField(upload_to='artworks/%Y/', verbose_name='Изображение')),
                ('is_featured', models.BooleanField(default=False, verbose_name='На главную')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_for_sale', models.BooleanField(default=False, verbose_name='В продаже (будущее)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (будущее)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Картина',
                'verbose_name_plural': 'Картины',
                'ordering': ['order', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название серии')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/details/%Y/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=220, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='gallery.artwork', verbose_name='Картина')),
            ],
            options={
                'verbose_name': 'Доп. фото картины',
                'verbose_name_plural': 'Доп. фото картин',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='gallery.series', verbose_name='Серия'),
        ),
    ]
