"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path):
    """Load KEY=VALUE lines into os.environ (no override, no extra deps).

    Used on Timeweb shared hosting where secrets live in ~/site/.env
    (chmod 600, NOT in git). Local dev keeps working with real env vars.
    """
    try:
        with open(path, 'r', encoding='utf-8') as f:
            for raw in f:
                line = raw.strip()
                if not line or line.startswith('#') or '=' not in line:
                    continue
                key, _, val = line.partition('=')
                key = key.strip()
                val = val.strip().strip('"').strip("'")
                if key and key not in os.environ:
                    os.environ[key] = val
    except (FileNotFoundError, NotADirectoryError, PermissionError):
        pass


# Order: explicit env file -> ~/site/.env (Timeweb) -> project .env (local) -> parent .env
for _env_path in (
    os.environ.get('DJANGO_ENV_FILE', ''),
    os.path.expanduser('~/site/.env'),
    str(BASE_DIR / '.env'),
):
    if _env_path:
        _load_dotenv(_env_path)


def _csv(name):
    return [v.strip() for v in os.environ.get(name, '').split(',') if v.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-g%0#=gl*b5s645ajjkk7!#)n218f3oqutc2)*=@2)a1v=&%q8p'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = _csv('DJANGO_ALLOWED_HOSTS')
if DEBUG:
    ALLOWED_HOSTS += ['127.0.0.1', 'localhost']

# CSRF: must include scheme, e.g. http://ct931410.tw1.ru (no SSL yet),
# after Let's Encrypt switch to https://your-domain.ru
CSRF_TRUSTED_ORIGINS = _csv('DJANGO_CSRF_TRUSTED_ORIGINS') or _csv('CSRF_TRUSTED_ORIGINS')

# Behind Timeweb Apache / Render TLS termination
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Keep False on http tech-domain (ct931410.tw1.ru); enable via env after HTTPS:
# DJANGO_SECURE_COOKIES=True
_SECURE_COOKIES = os.environ.get('DJANGO_SECURE_COOKIES', 'False') == 'True'
SESSION_COOKIE_SECURE = _SECURE_COOKIES
CSRF_COOKIE_SECURE = _SECURE_COOKIES


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'imagekit',
    'core',
    'gallery',
    'exhibitions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.artist_profile',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Matches 0001_initial migrations (already BigAutoField); silences models.W042.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# Priority: 1) MySQL via DB_* (Timeweb shared, HOST=localhost),
#           2) DATABASE_URL (Postgres, Render/Supabase),
#           3) SQLite (local dev).

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

_DB_NAME = os.environ.get('DB_NAME', '')
_DATABASE_URL = os.environ.get('DATABASE_URL', '')
if _DB_NAME:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': _DB_NAME,
        'USER': os.environ.get('DB_USER', _DB_NAME),
        'PASSWORD': os.environ.get('DB_PASS', os.environ.get('DB_PASSWORD', '')),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
elif _DATABASE_URL:
    try:
        import dj_database_url
        DATABASES['default'] = dj_database_url.parse(_DATABASE_URL, conn_max_age=600)
    except ImportError:
        pass


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Contact / email
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@example.com')
CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', 'artist@example.com')  # <-- поменяйте на почту художника

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Dev default: console. Prod (Timeweb SMTP): set EMAIL_HOST etc. in ~/site/.env.

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend' if os.environ.get('EMAIL_HOST') else 'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587') or '587')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10') or '10')
